// Auto-generated route index file
// Generated by scripts/build-routes.mjs

import { ClassView } from './lib/classview.mjs';

import Route0Module from './api/auth.mjs';
import route1 from './api/orders/list.mjs';
import Route2Module from './api/products.mjs';
import route3 from './api/users.mjs';

function wrapClassView(ViewClass) {
  if (ViewClass.prototype instanceof ClassView || ViewClass === ClassView) {
    return async (request, env, ctx) => {
      const instance = new ViewClass();
      return await instance.dispatch(request, env, ctx);
    };
  }
  return ViewClass;
}

export const routes = [
  ['/auth', wrapClassView(Route0Module.default || Route0Module)],
  ['/orders/list', route1],
  ['/products', wrapClassView(Route2Module.default || Route2Module)],
  ['/users', route3]
];