version: '3.8'

services:
  cloudflare-workers:
    build: .
    ports:
      - "3000:3000"
      - "8787:8787"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - NODE_ENV=development
    command: pnpm run dev