// Auto-generated route index file
// Generated by scripts/build-routes.mjs

import { ClassView } from '../lib/classview.mjs';

import Route0Module from './auth.mjs';
import route1 from './orders/list.mjs';
import route2 from './plugins.mjs';
import Route3Module from './products.mjs';
import route4 from './review.mjs';
import route5 from './users.mjs';

function wrapClassView(ViewClass) {
  if (ViewClass.prototype instanceof ClassView || ViewClass === ClassView) {
    return async (request, env, ctx) => {
      const instance = new ViewClass();
      return await instance.dispatch(request, env, ctx);
    };
  }
  return ViewClass;
}

export const routes = [
  ['/auth', wrapClassView(Route0Module.default || Route0Module)],
  ['/orders/list', route1],
  ['/plugins', route2],
  ['/products', wrapClassView(Route3Module.default || Route3Module)],
  ['/review', route4],
  ['/users', route5]
];